FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /app/go-api ./cmd/api
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/go-api .
COPY --from=builder /app/uploads ./uploads
EXPOSE 8080
CMD ["./go-api"]